mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  address: 0.0.0.0
spring:
  profiles:
    active: local
---
spring:
  application:
    name: hive-metadata
  profiles:
    local
  datasource:
    url: jdbc:mysql://localhost:3306/hivemetadata
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  application:
    name: hive-metadata
  profiles:
    prd
  datasource:
    url: jdbc:mysql://localhost:11856/hive
    username: hive
    password: hive
    driver-class-name: com.mysql.cj.jdbc.Driver